## PLOT #######################################################################
import matplotlib.pyplot as plt 
def fig(xx, vg, qvzp1, qvzp2, avg_qvzp1, avg_qvzp2, lxi, p0, fnx):
    plt.figure(1)
    plt.plot(xx, lxi, label=r'Contact Length $l_t/b$')
    plt.legend(())
    # plt.figure(2)
    # plt.plot(xx, qvzp1[0, 0, :], xx, qvzp2[0, 0, :], 'r--')
    # plt.subplot(211)
    # plt.plot(xx, p0[0, :], label='Hertzian Contact Pressure')
    # plt.ylabel(r'$p_0$ / Pa')
    # plt.subplot(212)
    # plt.plot(xx,  fnx[0, :],  'r--')
    # plt.ylabel(r'$Fnx$ / Nmm]')
    # plt.xlabel('\u03B6')
    # plt.legend('$Fnx$ / Nmm')
    # plt.figure(3)
    # plt.subplot(211)
    # plt.plot(xx, abs(vg[0, :]), label='Sliding Speed')
    # plt.ylabel(r'$v_g$ / ms')
    # plt.subplot(212) 
    # plt.plot(xx, avg_qvzp1[0, 0, :], xx, avg_qvzp2[0, 0, :], 'r--')
    # plt.legend(('Pinion', 'Wheel'))
    # plt.ylabel(r'$q_{vzp}$ / W')