## PLOT #######################################################################
import matplotlib.pyplot as plt 
def fig(xx, vg, qvzp1, qvzp2, avg_qvzp1, avg_qvzp2, lxi, p0, fnx, load, nmotor):
    plt.figure(1)
    plt.plot(xx, lxi)
    plt.xlabel('\u03B6')
    plt.ylabel(r'$L_t\left(x\right)/b$')
    plt.grid(True)
    plt.title('Total contact length over face width')
    for i in range(len(p0)):
        plt.figure(2)
        plt.plot(xx,  1e-3*fnx[i,:], label=load[i])
        plt.ylabel(r'$Fn\left(x\right)$ / Nmm$^{-1}$')
        plt.xlabel('\u03B6')
        plt.title('Load per face width')
        plt.grid(True)
        plt.legend()
        plt.figure(3)
        plt.plot(xx, p0[i,:]*1e-9,label=load[i])
        plt.ylabel(r'$p_0\left(x\right)$ / GPa')
        plt.title('Hertzian Contact Pressure')
        plt.xlabel('\u03B6')
        plt.grid(True)
        plt.legend()
    for j in range(len(nmotor)):
        plt.figure(4)
        plt.plot(xx, abs(vg[j, :]),label=str(int(nmotor[j]))+' rpm')
        plt.ylabel(r'$v_g\left(x\right)$ / ms$^{-1}$')
        plt.title('Sliding Speed')
        plt.xlabel('\u03B6')
        plt.grid(True)
        plt.legend()
    plt.figure(5)
    plt.plot(xx, qvzp1[-1,-1,:], xx, qvzp2[-1,-1,:], 'r--')
    plt.xlabel('\u03B6')
    plt.ylabel(r'$q_{vzp}\left(x\right)$ / Wm$^{-2}$')
    plt.title(r'Heat Flux - ' + load[-1]+' / '+str(int(nmotor[-1]))+' rpm')
    plt.legend(('Pinion', 'Wheel'))
    plt.grid(True)
    plt.figure(6) 
    plt.plot(xx, avg_qvzp1[-1,-1,:], xx, avg_qvzp2[-1,-1,:], 'r--')
    plt.legend(('Pinion', 'Wheel'))
    plt.xlabel('\u03B6')
    plt.ylabel(r'$\overline{q_{vzp}}\left(x\right)$ / Wm$^{-2}$')
    plt.grid(True)
    plt.title(r'Average heat flux - ' + load[-1]+' / '+str(int(nmotor[-1]))+' rpm')