## PLOT #######################################################################
import matplotlib.pyplot as plt 
def fig(xx, vg, qvzp1, qvzp2, avg_qvzp1, avg_qvzp2, lxi, p0, fnx):
    plt.figure(1)
    plt.plot(xx, lxi)
    plt.figure(2)
    plt.plot(xx, qvzp1[0, 0, :], xx, qvzp2[0, 0, :], 'r--')
    plt.subplot(211)
    plt.plot(xx, p0[0, :])
    plt.legend(('p0'))
    plt.ylabel('p0 [Pa]')
    plt.subplot(212)
    plt.plot(xx,  fnx[0, :],  'r--')
    plt.ylabel('Fnx [N/mm]')
    plt.xlabel('\u03B6 [-]')
    plt.legend('Fnx N/mm')
    plt.figure(3)
    plt.subplot(211)
    plt.plot(xx, abs(vg[0, :]))
    plt.legend(('vg'))
    plt.ylabel('vg [m/s]')
    plt.subplot(212) 
    plt.plot(xx, avg_qvzp1[0, 0, :], xx, avg_qvzp2[0, 0, :], 'r--')
    plt.legend(('P', 'W'))
    plt.ylabel('qvzp/W')
## PRINT GEAR GEOMETRY ##
def prt(gear, mat, alpha, beta, m, z, x, al, pb, rf, r, rl, ra, epslon_alpha, \
        epslon_beta, epslon_gama, Req, AB, AC, AD, AE, E, v, cpg, kg, rohg, \
        sigmaHlim, sigmaFlim, Pin, fbt, fbn, ft, fr, fn, fa, fbear, p0, p0p, \
        Tlub, miu, niu, piezo, HVL, COF, pvzp, pvl, pv):
    print('Gear type: ', gear)
    print('Gear material: ', mat)
    print('Presure angle (\u03B1): ', alpha)
    print('Helix angle (\u03B2): ', beta)
    print('Module [mm]: ', m)
    print('Number of teeth: ', z)
    print('Profile shift: ', x)
    print('Axis distance [mm]: ', al)
    print('Base pitch [mm]: ', pb)
    print('Root radius [mm]: ', rf)
    print('Reference radius [mm]: ', r)
    print('Pitch radius [mm]: ', rl)
    print('Tip radius [mm]: ', ra)
    print('\u03B5_\u03B1: ', epslon_alpha)
    print('\u03B5_\u03B2: ', epslon_beta)
    print('\u03B5_\u03B3: ', epslon_gama)
    print('Equivalent radius [mm]: ', Req)
    print('AB [mm]: ', AB)
    print('AC [mm]: ', AC)
    print('AD [mm]: ', AD)
    print('AE [mm]: ', AE)
    print('Young Modulus [Pa]: ', E)
    print('Poisson Ratio  [-]: ', v)
    print('Thermal capacity  [J/kg.K]: ', cpg)
    print('Thermal conductivity  [W/m.K]: ', kg)
    print('Density  [kg/m3]: ', rohg)
    print('\u03C3_{Hlim} [MPa]: ', sigmaHlim)
    print('\u03C3_{Flim} [MPa]: ', sigmaFlim)
    print('Pin [W]: ', Pin)
    print('F_bt [N]: ', fbt)
    print('F_bn [N]: ', fbn)
    print('F_t [N]: ', ft)
    print('F_r [N]: ', fr)
    print('F_n [N]: ', fn)
    print('F_a [N]: ', fa)
    print('F_bearings [N]: ', fbear)
    print('p_0 [Pa]: ', max(p0[0, :]))
    print('p_0p [Pa]: ', p0p)
    print('Tlub [\u03B1 C] ', Tlub)
    print('\u03B7 [mPas] ', miu)
    print('\u03BD [cSt] ', niu)
    print('\u03B1 [1/Pa] ', piezo)
    print('HVL [-] ', HVL)
    print('\u03BC_mZ [-] ', COF)
    print('Pvzp [W] ', pvzp)
    print('Pvl [W] ', pvl)
    print('Pv [W] ', pv)
